head.load(
	//"js/lib/jquery.js",
	"js/lib/jquery.reject.js",
	"js/lib/jquery.validate.min.js",
	"js/lib/jquery.activity.min.js",
	//"js/lib/jquery.fancybox.pack.js",
	"js/lib/social-likes.min.js",
	//"js/lib/bootstrap.min.js",
	"js/common.js"
);
